services:
  postgres:
    image: postgres:16
    container_name: tech_sys_postgres
    restart: always

    environment:
      POSTGRES_DB: tech_sys_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 55005

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: